### ISSUE TITLE
8 Ball Pool consistent crashing right after opening the application

### ISSUE THREAD

**Issue by zekgt** [OiwexO/PoolPredictor#5]
Please bear with me Sir.

Basically the app crashes right after opening it and gives this error code

```
java.lang.VerifyError: Verifier rejected class com.miniclip.eightballpool.EightBallPoolActivity: void com.miniclip.eightballpool.EightBallPoolActivity.$$i(short, short, short, java.lang.Object[]) failed to verify: void com.miniclip.eightballpool.EightBallPoolActivity.$$i(short, short, short, java.lang.Object[]): [0x22] register v6 has type Precise Reference: java.lang.String but expected Reference: android.content.Context (declaration of 'com.miniclip.eightballpool.EightBallPoolActivity' appears in /data/app/~~XKxXoBQnnkKsdATZTY9nKQ==/com.miniclip.eightballpool-uuoR5SxomkHzcaRma_deLA==/base.apk!classes6.dex)
	at java.lang.Class.newInstance(Native Method)
	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
	at androidx.core.app.CoreComponentFactory.instantiateActivity(:45)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1362)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3797)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4062)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2415)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8410)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
	
```

The error has to do with steps 9-10, I purposefully put the copied code (from **predictor\smali\com\iwex\poolpredictor\MainActivity.smali**); I pasted the copied code into another method (onResume) instead of onCreate and if I pasted the code into the latter method (onCreate) it would give an error during the compilation of the APK (8Ball with the modded embedded) this is the error:

```
[21:01:00] ..\8BallFolder\smali_classes6\com\miniclip\eightballpool\EightBallPoolActivity.smali[1687,4] Invalid register: v31. Must be between v0 and v15, inclusive.
[21:01:00] Could not smali file: com/miniclip/eightballpool/EightBallPoolActivity.smali
[21:01:01] =====[ Error ]=====
[21:01:01] Compiling failed

// For context this is line 1687
move-object v1, p0
```

And if there was no compile error and the copied code was pasted on onCreate method it would give another error:
```
java.lang.RuntimeException: Unable to instantiate application com.miniclip.eightballpool.EightBallPoolApplication package com.miniclip.eightballpool: java.lang.ClassNotFoundException: o._build
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1493)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1422)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7196)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2241)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8410)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.lang.ClassNotFoundException: o._build
	at o.getData.getData(:1094)
	at java.lang.reflect.Method.invoke(Native Method)
	at o.ByteStringStoreKt.<clinit>(:2478)
	at com.miniclip.eightballpool.EightBallPoolApplication.attachBaseContext(Unknown Source:140)
	at android.app.Application.attach(Application.java:358)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1253)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1485)
	... 11 more
	// Apologies I cannot access the last 11 lines.
```

There was approximately 10 smali folders in the decompiled apk of the mod menu, is this an issue or not or there should only be one smali folder?

And for the last question, is it necessary to update the offsets to the latest version or does it automatically update? I know that this is a dumb question, but I saw some other *clients* have the offsets automatically update after each game update.

Please bear with me and I hope for your kind consideration and help.

**Comment by OiwexO** [comment]
> There was approximately 10 smali folders in the decompiled apk of the mod menu.

That's because you have built a debug APK. Debug build won't inject into the game. You have to build a release APK.

> is it necessary to update the offsets to the latest version or does it automatically update?

As the readme file says:
> This mod only works with 8 Ball Pool version 5.8.0 armeabi-v7a (32-bit). You can't use it in online matches.

**Comment by zekgt** [comment]
I have finally made a successful build of the release apk and managed to embed it into 8 Ball Pool but I'm curious,
> > This mod only works with 8 Ball Pool version 5.8.0 armeabi-v7a (32-bit). You can't use it in online matches.
What aspect of this mod makes it unusable for online matches?

**Comment by OiwexO** [comment]
8 ball pool v. 5.8.0 is disconnected from the game server. And new versions of the game have protection against modification and reverse engineering. + Offsets aren't updated automatically
